USE [QTC-Dashboard]
GO

CREATE USER [nonprod\devsvc_QTC-Dashboard] FOR LOGIN [nonprod\devsvc_QTC-Dashboard]
GO

/*
CREATE ROLE [SVC_EFMH_ROLE]
GO

ALTER ROLE [SVC_EFMH_ROLE] ADD MEMBER [nonprod\devsvc_EFMH]
ALTER ROLE [DB_DATAREADER] ADD MEMBER [SVC_EFMH_ROLE]
ALTER ROLE [DB_DATAWRITER] ADD MEMBER [SVC_EFMH_ROLE]
GO
*/